export const data = [
    {
        id: 1,
        first_name: "Lesley",
        last_name: "Brignall",
        email: "lbrignall0@fc2.com",
        gender: "Male",
        company: "Trudeo",
        picture: "http://dummyimage.com/170x100.png/dddddd/000000",
    },
    {
        id: 2,
        first_name: "Finn",
        last_name: "Sinney",
        email: "fsinney1@arstechnica.com",
        gender: "Male",
        company: "Fanoodle",
        picture: "http://dummyimage.com/182x100.png/cc0000/ffffff",
    },
    {
        id: 3,
        first_name: "Arlyn",
        last_name: "Gorrick",
        email: "agorrick2@ustream.tv",
        gender: "Female",
        company: "Leenti",
        picture: "http://dummyimage.com/111x100.png/5fa2dd/ffffff",
    },
    {
        id: 4,
        first_name: "Pattie",
        last_name: "Robel",
        email: "probel3@youku.com",
        gender: "Female",
        company: "Tagopia",
        picture: "http://dummyimage.com/230x100.png/dddddd/000000",
    },
    {
        id: 5,
        first_name: "Reginauld",
        last_name: "Parkes",
        email: "rparkes4@miibeian.gov.cn",
        gender: "Male",
        company: "Edgetag",
        picture: "http://dummyimage.com/105x100.png/cc0000/ffffff",
    },
    {
        id: 6,
        first_name: "Isaak",
        last_name: "Faithfull",
        email: "ifaithfull5@smh.com.au",
        gender: "Male",
        company: "Zoonoodle",
        picture: "http://dummyimage.com/187x100.png/ff4444/ffffff",
    },
    {
        id: 7,
        first_name: "Olag",
        last_name: "Warboys",
        email: "owarboys6@delicious.com",
        gender: "Male",
        company: "Browsecat",
        picture: "http://dummyimage.com/184x100.png/cc0000/ffffff",
    },
    {
        id: 8,
        first_name: "Jeremy",
        last_name: "Cosins",
        email: "jcosins7@lulu.com",
        gender: "Male",
        company: "Topicware",
        picture: "http://dummyimage.com/172x100.png/5fa2dd/ffffff",
    },
    {
        id: 9,
        first_name: "Geordie",
        last_name: "Dufore",
        email: "gdufore8@bandcamp.com",
        gender: "Male",
        company: "Realbuzz",
        picture: "http://dummyimage.com/189x100.png/cc0000/ffffff",
    },
    {
        id: 10,
        first_name: "Christos",
        last_name: "Sharma",
        email: "csharma9@mozilla.com",
        gender: "Male",
        company: "Wikizz",
        picture: "http://dummyimage.com/232x100.png/cc0000/ffffff",
    },
];
